name: CI ML Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t olist-ml-engine:ci .

    - name: Crear carpetas necesarias en Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/app olist-ml-engine:ci bash -c "\
        mkdir -p /app/models /app/reports/results /app/reports/figures"

    - name: Run notebooks in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/app olist-ml-engine:ci bash -c "\
        for notebook in $(find /app -name '*.ipynb'); do \
          jupyter nbconvert --to notebook --execute \$notebook --inplace; \
        done"